### ISSUE TITLE
백엔드 설계 - 회원

### ISSUE THREAD

**Issue by chchcoco** [project-TravleJ/backend#2]
## todo list

- [x] 회원 가입
- [x] 회원 전체 조회
- [x] 회원 닉네임 별 상세 조회
- [x] 회원 등급 별 상세 조회
- [x] 회원 상태 별 상세 조회
- [x] 회원 가입일 별 상세 조회
- [x] 회원 최종 접속일 별 상세 조회
- [x] 회원 수정
- [ ] 회원 탈퇴(무기한 정지)
- [x] 로그인
- [ ] 비밀번호 변경
- [ ] 프로필 사진 변경
